### ISSUE TITLE
`triangle()` when using left or right `$direction` reverses `$width` and `$height` params.

### ISSUE THREAD

**Issue by azinasili** [azinasili/bytes#16]
See below code for fix: 

```scss
@mixin triangle($width, $height: $width, $color: #000, $direction: 'bottom') {
  $_height: ($height / 2);
  $_width: ($width / 2);
  $_sides: (
    'top': (
      'border-bottom': $height solid $color,
      'border-left': $_width solid transparent,
      'border-right': $_width solid transparent,
    ),
    'right': (
      'border-left': $width solid $color,
      'border-top': $_height solid transparent,
      'border-bottom': $_height solid transparent,
    ),
    'bottom': (
      'border-top': $height solid $color,
      'border-left': $_width solid transparent,
      'border-right': $_width solid transparent,
    ),
    'left': (
      'border-right': $width solid $color,
      'border-top': $_height solid transparent,
      'border-bottom': $_height solid transparent,
    ),
  );
  $_angles: (
    'topLeft': (
      'border-top-color': $color,
      'border-left-color': $color,
    ),
    'topRight': (
      'border-top-color': $color,
      'border-right-color': $color,
    ),
    'bottomLeft': (
      'border-bottom-color': $color,
      'border-left-color': $color,
    ),
    'bottomRight': (
      'border-bottom-color': $color,
      'border-right-color': $color,
    ),
  );
  $_directions: map-merge($_sides, $_angles);
  $_angle-check: map-has-key($_angles, $direction);

  @if not map-has-key($_directions, $direction) {
    @error '`#{$direction}` is not a valid argument for `triangle()`, please use one of the following: #{map-keys($_directions)}';
  }
  display: inline-block;
  @if $width == $height and $_angle-check {
    border: $_width solid transparent;
    @include set(get($_angles, $direction));
  } @else {
    @if $_angle-check {
      @error '`triangle()` $width and $height must be the same to use `#{$direction}`';
    }
    @include set(get($_sides, $direction));
  }
}
```
